[project]
name = 'Decentralized-Reality-Simulation-Marketplace'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.experience-licensor]
path = 'contracts/experience-licensor.clar'
clarity_version = 2
epoch = 2.5

[contracts.virtual-universe-creator]
path = 'contracts/virtual-universe-creator.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
